[package]
name = "tinybox"
version = "0.5.0"
description = "Like `Box`, but with an optimization that avoids allocations for small data-structures"
authors = ["Christoph Hommelsheim <main@chommel.eu>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/HellButcher/tinybox-rs.git"
keywords = ["box", "collection", "dyn", "dst"]
categories = ["data-structures", "no-std"]
readme = "README.md"
edition = "2024"
rust-version = "1.99"

[features]
# allow to use unstable features of Rust (nightly)
unstable = []

[lints.rust]
deprecated_safe = "warn"
future_incompatible = "warn"
missing_docs = "warn"
raw_borrows_via_references = "warn"
redundant_imports = "warn"
redundant_lifetimes = "warn"
rust_2018_idioms = "warn"
single_use_lifetimes = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unknown_or_malformed_diagnostic_attributes = "warn"
unsafe_attr_outside_unsafe = "warn"
unused = "warn"
unused_crate_dependencies = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
unused_qualifications = "warn"

[lints.clippy]
alloc_instead_of_core = "warn"
allow_attributes_without_reason = "warn"
cargo = "warn"
dbg_macro = "warn"
doc_paragraphs_missing_punctuation = "warn"
fallible_impl_from = "warn"
infinite_loop = "warn"
pedantic = "warn"
print_stderr = "warn"
print_stdout = "warn"
redundant_pub_crate = "warn"
suspicious_operation_groupings = "warn"
undocumented_unsafe_blocks = "warn"
unimplemented = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unnecessary_self_imports = "warn"
use_self = "warn"
useless_let_if_seq = "warn"
wildcard_imports = "warn"

